### ISSUE TITLE
Thermal labels

### ISSUE THREAD

**Issue by seawee1** [chelicynly/A-Deep-Learning-Approach-to-Drone-Monitoring#3]
Hi, I'd like to use the thermal usc drone dataset. The ''images and labels'' folder however only contains two drone sequences and the labels are missing. For the 10 videos that are provided I also couldn't find any labels.

**Comment by seawee1** [comment]
I labeled the thermal part of the dataset by myself. If someone is interested, contact me.

**Comment by MuhammadAsadJaved** [comment]
@seawee1  Can you share the labels Please? asadjavedgujar@gmail.com

Thanks

**Comment by seawee1** [comment]
Dear Asad,

here you go. Could take a day until Google Drive will not raise the quota
error however.
https://drive.google.com/file/d/1oc4xCwpsaeXUAh_EqWYb0hzC6rhIcqWe/view?usp=sharing

I don't think I labeled all of the TIR images, but it should be around a
few thousand labels or so. I can't really remember.
As daytime data only had keyframe annotations, I added some additional
labels in between keyframes for better bounding box interpolation results
on these images.

The pre-processed dataset is in ImageNet format and also includes 2 TIR
drone sequences of the Linkping Thermal InfraRed (LTIR) dataset. If you
need more information about how the pre-processed dataset was created, I
can send you an excerpt of my masters thesis.

Greetings
Sebastian Rietsch

Am Di., 15. Sept. 2020 um 04:58 Uhr schrieb Asad <notifications@github.com>:

**Comment by MuhammadAsadJaved** [comment]
Dear  Sebastian Rietsch,
                                          Thank you so much for your
cooperation. They also provide some annotations (only for detection
results) for Thermal dataset in the Thermal_data/videos/Detection Results/
folder.  But all the annotations are in one .txt format.  I have converted
them to voc/coc format (in .txt and .xml) format. if you can then let
me know.
I will share it with you. or I will only share the python program and you
can do by yourself. it can also use for other sets. Thanks
Sebastian Rietsch
